steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/peaceful-signer-481816-n7/hello-repo/app:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/peaceful-signer-481816-n7/hello-repo/app:$COMMIT_SHA']

options:
  logging: CLOUD_LOGGING_ONLY

images:
- 'us-central1-docker.pkg.dev/peaceful-signer-481816-n7/hello-repo/app:$COMMIT_SHA'

